CustomUnit:
  is_enabled: true
  debug: false
  # Path to folder with units
  unit_path: C:\Users\valge\AppData\Roaming\EXILED\Units
  # Options for events. You can set only 1 option per event
  options:
    PlayerDying:
      is_enabled: true # If false - this event won't affect anything
      chance: 100 # Chance that event will add tickets
      allow: # If player that fired that event has this role - event will add tickets (not ignoring checks above)
      - ChaosConscript
      - ClassD
      disallow: # If player that fired that event has this role - event won't add tickets
      - FacilityGuard
      - NtfPrivate
